name: flutter_application_1
description: "Телеметрия планера — GPS карта и управление"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  flutter_compass: ^0.8.1
  flutter_blue_plus: ^1.32.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0   # 👈 ДОБАВЛЕНО для смены иконки

flutter:
  uses-material-design: true

  # 👇 ДОБАВЛЕН ЭТОТ БЛОК (ассеты)
  assets:
    - assets/icon/icon.png

# 👇 ДОБАВЛЕН ЭТОТ БЛОК (настройки иконки)
flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true